### ISSUE TITLE
Read the  parameters from a configuration file

### ISSUE THREAD

**Issue by rupinr** [RAZERZ/PullFlightData#1]
It would be great to read the api parameters and db connection credentials from a file instead of hard coding it.

**Comment by rupinr** [comment]
If you think that is a good idea, i can work on it..

**Comment by RAZERZ** [comment]
I wouldn't consider the credentials hard coded, since they are stored in a variable (the instance of the mysqli() class). Moving them to a separate page/file would cause confusion :)
